-- Schema PostgreSQL compatibile con Aiven.
-- Questo script e' non distruttivo e non crea account dimostrativi.
-- Eseguirlo manualmente una volta sul database prima di avviare l'applicazione.

CREATE TABLE IF NOT EXISTS Users (
    id_user INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    surname VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'user',
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(32) NULL,
    password VARCHAR(60) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active'
);

CREATE INDEX IF NOT EXISTS idx_users_status ON Users (status);
CREATE UNIQUE INDEX IF NOT EXISTS uk_users_email ON Users (LOWER(email));

ALTER TABLE Users ADD COLUMN IF NOT EXISTS phone VARCHAR(32) NULL;

CREATE TABLE IF NOT EXISTS AccountVerification (
    id_verification BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purpose VARCHAR(32) NOT NULL,
    id_user INTEGER NULL,
    email VARCHAR(255) NOT NULL,
    name VARCHAR(255) NULL,
    surname VARCHAR(255) NULL,
    password_hash VARCHAR(60) NULL,
    code_hash VARCHAR(60) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_verification_user FOREIGN KEY (id_user)
        REFERENCES Users (id_user) ON DELETE CASCADE,
    CONSTRAINT chk_verification_purpose CHECK (purpose IN
        ('register', 'forgot_password', 'change_password', 'change_email')),
    CONSTRAINT chk_verification_attempts CHECK (attempts BETWEEN 0 AND 5)
);

CREATE INDEX IF NOT EXISTS idx_verification_email
    ON AccountVerification (purpose, LOWER(email));
CREATE INDEX IF NOT EXISTS idx_verification_user
    ON AccountVerification (purpose, id_user) WHERE id_user IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_verification_expiry
    ON AccountVerification (expires_at);

-- Prima di imporre l'unicita', conserva soltanto la richiesta piu' recente
-- per scopo/account. Le righe eliminate sono codici gia' sostituiti e quindi
-- non devono piu' poter essere usati.
WITH duplicate_verifications AS (
    SELECT id_verification,
           ROW_NUMBER() OVER (
               PARTITION BY purpose, id_user
               ORDER BY id_verification DESC
           ) AS position
    FROM AccountVerification
    WHERE id_user IS NOT NULL
)
DELETE FROM AccountVerification
WHERE id_verification IN (
    SELECT id_verification FROM duplicate_verifications WHERE position > 1
);

WITH duplicate_verifications AS (
    SELECT id_verification,
           ROW_NUMBER() OVER (
               PARTITION BY purpose, LOWER(email)
               ORDER BY id_verification DESC
           ) AS position
    FROM AccountVerification
    WHERE id_user IS NULL
)
DELETE FROM AccountVerification
WHERE id_verification IN (
    SELECT id_verification FROM duplicate_verifications WHERE position > 1
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_verification_user
    ON AccountVerification (purpose, id_user) WHERE id_user IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uk_verification_email
    ON AccountVerification (purpose, (LOWER(email))) WHERE id_user IS NULL;

-- Sessioni HTTP condivise fra piu' istanze dell'applicazione.
CREATE TABLE IF NOT EXISTS SPRING_SESSION (
    PRIMARY_ID CHAR(36) NOT NULL,
    SESSION_ID CHAR(36) NOT NULL,
    CREATION_TIME BIGINT NOT NULL,
    LAST_ACCESS_TIME BIGINT NOT NULL,
    MAX_INACTIVE_INTERVAL INTEGER NOT NULL,
    EXPIRY_TIME BIGINT NOT NULL,
    PRINCIPAL_NAME VARCHAR(100),
    CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX IF NOT EXISTS SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX IF NOT EXISTS SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE IF NOT EXISTS SPRING_SESSION_ATTRIBUTES (
    SESSION_PRIMARY_ID CHAR(36) NOT NULL,
    ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
    ATTRIBUTE_BYTES BYTEA NOT NULL,
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID)
        REFERENCES SPRING_SESSION (PRIMARY_ID) ON DELETE CASCADE
);

-- Rate limit condiviso e atomico anche con piu' istanze del backend.
CREATE TABLE IF NOT EXISTS RequestRateLimit (
    scope VARCHAR(100) NOT NULL,
    client_id VARCHAR(255) NOT NULL,
    window_started_at TIMESTAMPTZ NOT NULL,
    requests INTEGER NOT NULL,
    CONSTRAINT pk_request_rate_limit PRIMARY KEY (scope, client_id),
    CONSTRAINT chk_request_rate_limit_requests CHECK (requests > 0)
);

CREATE INDEX IF NOT EXISTS idx_request_rate_limit_window
    ON RequestRateLimit (window_started_at);

CREATE TABLE IF NOT EXISTS PostGeneralInfo (
    id_post INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user INT NOT NULL,
    photo1 BYTEA NULL,
    photo2 BYTEA NULL,
    photo3 BYTEA NULL,
    price DECIMAL(12,2) NOT NULL,
    complete_address VARCHAR(255) NOT NULL,
    latitude DECIMAL(10,8) NOT NULL,
    longitude DECIMAL(11,8) NOT NULL,
    show_phone BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_posts_user FOREIGN KEY (id_user) REFERENCES Users (id_user)
);

CREATE INDEX IF NOT EXISTS idx_posts_search
    ON PostGeneralInfo (status, price, latitude, longitude);
CREATE INDEX IF NOT EXISTS idx_posts_user ON PostGeneralInfo (id_user);

ALTER TABLE PostGeneralInfo ADD COLUMN IF NOT EXISTS show_phone BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS Desktop (
    id_post INT PRIMARY KEY,
    cpu VARCHAR(255) NOT NULL,
    motherboard VARCHAR(255) NOT NULL,
    gpu VARCHAR(255) NOT NULL,
    ram VARCHAR(255) NOT NULL,
    memory VARCHAR(255) NOT NULL,
    power VARCHAR(255) NOT NULL,
    cpu_heat VARCHAR(255) NOT NULL,
    pc_case VARCHAR(255) NOT NULL,
    CONSTRAINT fk_desktop_post FOREIGN KEY (id_post)
        REFERENCES PostGeneralInfo (id_post) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Laptop (
    id_post INT PRIMARY KEY,
    brand VARCHAR(255) NOT NULL,
    model VARCHAR(255) NOT NULL,
    screen_size DECIMAL(5,2) NOT NULL,
    cpu VARCHAR(255) NOT NULL,
    gpu VARCHAR(255) NOT NULL,
    ram VARCHAR(255) NOT NULL,
    memory VARCHAR(255) NOT NULL,
    CONSTRAINT fk_laptop_post FOREIGN KEY (id_post)
        REFERENCES PostGeneralInfo (id_post) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ListingReport (
    id_report INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_post INTEGER NOT NULL,
    id_user INTEGER NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_report_post FOREIGN KEY (id_post) REFERENCES PostGeneralInfo (id_post) ON DELETE CASCADE,
    CONSTRAINT fk_report_user FOREIGN KEY (id_user) REFERENCES Users (id_user) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_report_user
    ON ListingReport (id_post, id_user) WHERE id_user IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_report_post ON ListingReport (id_post);
