CREATE TABLE IF NOT EXISTS ListingReport (
    id_report INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_post INTEGER NOT NULL,
    id_user INTEGER NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_report_post FOREIGN KEY (id_post) REFERENCES PostGeneralInfo (id_post) ON DELETE CASCADE,
    CONSTRAINT fk_report_user FOREIGN KEY (id_user) REFERENCES Users (id_user) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_report_user
    ON ListingReport (id_post, id_user) WHERE id_user IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_report_post ON ListingReport (id_post);
